### ISSUE TITLE
Trying runnig server

### ISSUE THREAD

**Issue by jboss38** [Bcl32/ML_IDS_Dashboard#2]
Env : Windows 10 / Python 2.7+

Interrested in this solution, could you tell me all the requirements to run it ? 

```
C:\Users\Blitz\Documents\ML_IDS_Dashboard-master>python manage.py runserver
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x05E57EF0>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\utils\autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\core\management\commands\runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Python27\lib\site-packages\django\core\checks\registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Python27\lib\site-packages\django\core\checks\urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "C:\Python27\lib\site-packages\django\core\checks\urls.py", line 26, in check_resolver
    return check_method()
  File "C:\Python27\lib\site-packages\django\urls\resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Python27\lib\site-packages\django\urls\resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Python27\lib\site-packages\django\urls\resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Users\Blitz\Documents\ML_IDS_Dashboard-master\ids_v1\urls.py", line 21, in <module>
    url(r'^app1/', include('app1.urls')),
  File "C:\Python27\lib\site-packages\django\conf\urls\__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Users\Blitz\Documents\ML_IDS_Dashboard-master\app1\urls.py", line 2, in <module>
    from . import views
  File "C:\Users\Blitz\Documents\ML_IDS_Dashboard-master\app1\views.py", line 185
    def agglomerative_alg(df,*argv,file_type='svg',path_to_save=output_path):
                                           ^
SyntaxError: invalid syntax

```

**Comment by Bcl32** [comment]
Project Uses Python3.6
